# Generated by Django 4.0.2 on 2022-08-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='catagory',
            field=models.CharField(default='Article', max_length=50),
        ),
    ]
