# Generated by Django 4.0.2 on 2022-08-18 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_posts_like_posts_unlike_alter_likes_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('username', 'posts')},
        ),
    ]
