# Generated by Django 4.0.2 on 2022-08-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_posts_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='attachment',
        ),
    ]
