# Generated by Django 4.0.2 on 2022-08-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_posts_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='hashtag',
        ),
    ]
