# Generated by Django 4.0.2 on 2022-08-17 04:43

import catagories.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('username', models.ForeignKey(null=True, on_delete=catagories.models.superuser, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
