# Generated by Django 4.0.2 on 2022-08-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0002_catagory_delete_catagories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
