# Generated by Django 4.0.2 on 2022-08-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0003_alter_catagory_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='desc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
