# Generated by Django 4.0.2 on 2022-08-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0004_alter_catagory_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
