# Generated by Django 4.0.2 on 2022-08-25 18:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('desc', ckeditor.fields.RichTextField(blank=True, default=None)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('portfolio', models.CharField(blank=True, max_length=255)),
                ('professional_mail', models.CharField(blank=True, max_length=255)),
                ('domain_expert', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
