# Generated by Django 4.0.2 on 2022-08-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstype',
            name='domain_expert',
        ),
        migrations.RemoveField(
            model_name='userstype',
            name='img',
        ),
    ]
