# Generated by Django 4.0.2 on 2022-08-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_follow_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='inventor',
            new_name='incubator',
        ),
        migrations.AddField(
            model_name='profile',
            name='investor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner',
            field=models.BooleanField(default=False),
        ),
    ]
