# Generated by Django 4.0.2 on 2022-08-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_inventor_profile_incubator_profile_investor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_no',
        ),
    ]
