# Generated by Django 4.0.2 on 2022-08-22 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0012_remove_profile_bio_remove_profile_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
