# Generated by Django 4.0.2 on 2022-08-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='hashtag',
        ),
    ]
