# Generated by Django 4.0.2 on 2022-08-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questions_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questions.questions'),
        ),
    ]
