# Generated by Django 4.0.2 on 2022-08-23 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_remove_questions_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='answer',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
