# Generated by Django 4.0.2 on 2022-08-19 20:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ideas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtag', '0003_delete_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doi', models.CharField(default=None, max_length=255, unique=True)),
                ('url', models.CharField(default=None, max_length=255, unique=True)),
                ('desc', ckeditor.fields.RichTextField()),
                ('hashtag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hashtag.hashtag')),
                ('user', models.ForeignKey(null=True, on_delete=ideas.models.superuser, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
