# Generated by Django 4.0.2 on 2022-08-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_date_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='date',
            name='start_date',
        ),
        migrations.AddField(
            model_name='date',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
