# Generated by Django 4.0.2 on 2022-08-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_alter_available_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='day',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Monday', max_length=3),
        ),
    ]
