# Generated by Django 4.0.2 on 2022-08-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
