# Generated by Django 4.0.2 on 2022-08-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resources_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='resources/'),
        ),
    ]
