# Generated by Django 4.0.2 on 2022-08-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resources_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='description',
            new_name='desc',
        ),
    ]
