# Generated by Django 4.0.2 on 2022-08-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_rename_description_resources_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='image',
        ),
    ]
