# Generated by Django 4.0.2 on 2022-08-24 06:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_books_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeCourseBookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('desc', ckeditor.fields.RichTextField()),
                ('type', models.CharField(choices=[('Schemes', 'Schemes'), ('Course', 'Course'), ('Book', 'Book'), ('Event', 'Event'), ('TermsAndCondition', 'TermsAndCondition'), ('PrivacyPolicy', 'PrivacyPolicy')], default=None, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
